### ISSUE TITLE
Populate Java Objects from HTML with Thymeleaf; send DTO to Service

### ISSUE THREAD

**Issue by belmonjd1** [belmonjd1/PantryPal#12]

**Comment by aidandahm** [comment]
All commits for issues 11 and 12 were pushed to the 'Aidan - issues 11 and 12" branch. Review for possible errors.

**Comment by aidandahm** [comment]
Not marking complete until reviewed

**Comment by belmonjd1** [comment]
This issue was completed in the following commit: [https://github.com/belmonjd1/PantryPal/commit/99c2e485a8c31f6c9387b6f2363033c208e43c53](url)
